# Generated by Django 3.2.4 on 2021-06-08 21:02
from phonenumber_field.modelfields import PhoneNumberField
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ]

    operations = [migrations.CreateModel(name='City',
        fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('name', models.CharField(help_text='City', max_length=128)), ], ), migrations.CreateModel(name='Company',
        fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('name', models.CharField(help_text='Name of the company', max_length=128)),
            ('description', models.TextField(help_text='Brief description of the company', max_length=1000)),
            ('phone', PhoneNumberField(blank=True, help_text='Company phone number', max_length=31)),
            ('email', models.EmailField(blank=True, help_text='Company email', max_length=254)),
            ('telegram', models.URLField(blank=True, help_text='Company Telegram')),
            ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='app.city')), ], ),
        migrations.CreateModel(name='Country', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('name', models.CharField(help_text='Country', max_length=128, unique=True)), ], ),
        migrations.CreateModel(name='CountryAdmin', fields=[('country_ptr', models.OneToOneField(auto_created=True,
            on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False,
            to='app.country')), ], bases=('app.country',), ), migrations.CreateModel(name='Project', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('name', models.CharField(help_text='Name of the project', max_length=128)),
            ('description', models.TextField(help_text='Project description', max_length=5000)),
            ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')), ], ),
        migrations.CreateModel(name='Employee', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), (
            'role', models.CharField(choices=[('o', 'Owner'), ('e', 'Employee')], help_text='Role in the company',
                max_length=1)),
            ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)), ], ),
        migrations.AddField(model_name='company', name='employee',
            field=models.ManyToManyField(through='app.Employee', to=settings.AUTH_USER_MODEL), ),
        migrations.AddField(model_name='city', name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.country'), ), ]
