# Generated by Django 3.2.4 on 2021-06-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('app', '0001_initial'), ]

    operations = [migrations.AlterField(model_name='company', name='description',
        field=models.TextField(help_text='Brief description of the company', max_length=5000), ),
        migrations.DeleteModel(name='CountryAdmin', ), ]
