# Generated by Django 3.2.4 on 2021-06-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('app', '0002_auto_20210609_0033'), ]

    operations = [migrations.AddField(model_name='company', name='site',
        field=models.URLField(blank=True, help_text='Site of the company'), ), ]
