# Generated by Django 3.2.4 on 2021-06-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('app', '0003_company_site'), ]

    operations = [migrations.AlterField(model_name='company', name='telegram',
        field=models.URLField(blank=True, help_text='Company Telegram contact'), ), ]
