# Generated by Django 3.2.4 on 2021-06-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('app', '0005_alter_company_telegram'), ]

    operations = [migrations.AlterField(model_name='company', name='description',
        field=models.TextField(blank=True, help_text='Brief description of the company', max_length=5000), ), ]
