# Generated by Django 3.2.4 on 2021-06-15 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('app', '0007_alter_company_phone'), ]

    operations = [migrations.AddField(model_name='company', name='logo_img',
        field=models.ImageField(default='img/logo/no-logo.png', upload_to='img/logo/company/'), ),
        migrations.AlterField(model_name='employee', name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees',
                to='app.company'), ), migrations.AlterField(model_name='employee', name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies',
                to=settings.AUTH_USER_MODEL), ), migrations.AlterField(model_name='project', name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects',
                to='app.company'), ), ]
