# Generated by Django 3.2.4 on 2021-06-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('app', '0008_auto_20210615_2155'), ]

    operations = [migrations.AlterField(model_name='company', name='logo_img',
        field=models.ImageField(default='static/img/logo/no-logo.png', upload_to='static/img/logo/company/'), ), ]
