# Generated by Django 3.2.4 on 2021-06-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('app', '0009_alter_company_logo_img'), ]

    operations = [migrations.AddField(model_name='project', name='logo_img',
        field=models.ImageField(default='static/img/logo/no-logo.png', upload_to='static/img/logo/company/'), ), ]
